apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-listing-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "watch", "patch"]
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [list, watch]
- apiGroups: [""]
  resources: [namespaces]
  verbs: [list, watch]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-listing-rolebinding
subjects:
- kind: ServiceAccount
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
roleRef:
  kind: ClusterRole
  name: node-listing-role
  apiGroup: rbac.authorization.k8s.io